### ISSUE TITLE
Check IntervalTree decode function

### ISSUE THREAD

**Issue by Ybrin** [cryptoeconomicslab/wakkanay#203]
I think I found a potential bug in the `IntervalTree` implementation for dynamic address sizes, or even just for Ethereum addresses.

Please check the following:

https://github.com/cryptoeconomicslab/wakkanay/blob/master/packages/merkle-tree/src/IntervalTree.ts#L28-L34

@tkmct @syuhei176 I don't want to bias you. So please tell me why this function is correct in your opinion before I tell you what I think is wrong with it.

**Comment by syuhei176** [comment]
@Ybrin Hi, Thanks!

1. I'm going to replace this decode and encode method to `Coder.encode` and `Coder.decode` like below. This is because we should use L1 specific encoding to decode IntervalTreeNode in smart contract.

https://github.com/cryptoeconomicslab/wakkanay/blob/810b97e68e7b01d650331f51fc70fdf14deeef49/packages/plasma/src/types/StateUpdate.ts#L74

2. IMO, current implementation is correct when the size of `b` is 64 bytes.

`b.split(32)` splits `b` to 32bytes bytes as `d`. So, both d[0] and d[1] are 32 bytes.

**Comment by Ybrin** [comment]
Yes this seems to be correct. I have just mistaken this with the AddressTree.

https://github.com/cryptoeconomicslab/wakkanay/blob/master/packages/merkle-tree/src/AddressTree.ts#L19-L20

If the split function splits it to 32 byte arrays, d[1] will be 32 bytes, fixed. Currently my implementation supports dynamic address sizes, as some chains may opt to a non standard address size. Ethereum has for example 20 bytes.

**Comment by syuhei176** [comment]
@Ybrin oh you're right. We should encode Address to 32 bytes Bytes.
